# Project information
site_name: QuasarGUI
site_author: Barnabas Szabolcs
site_url: https://github.com/BarnabasSzabolcs/pyquasargui
site_description: >-
  Create modern desktop apps in Python.

# Repository
repo_name: BarnabasSzabolcs/pyquasargui
repo_url: https://github.com/BarnabasSzabolcs/pyquasargui
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2021 Barnabas Szabolcs

theme:
  name: material

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - content.tabs.link
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: assets/logo4.png
  logo: assets/logo4.png
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mermaid@8.5.1.min.js

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - markdown_include.include
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: BarnabasSzabolcs
      repo: pyquasargui
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Components: components.md
#  - Getting started:
#      - Installation: index.md
#      - Examples: index.md

plugins:
#  - minify:
#      minify_html: true